# Generated by Django 2.2.3 on 2019-08-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
